name: Daily Diet WhatsApp

on:
  schedule:
    - cron: '30 22 * * *'   # runs at 07:30 JST = 22:30 UTC
  workflow_dispatch:         # allows manual trigger

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install twilio python-dotenv
      - name: Run script
        run: python send_once.py
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_WHATSAPP_FROM: ${{ secrets.TWILIO_WHATSAPP_FROM }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
